### ISSUE TITLE
a tag should properly handle links with `---` in

### ISSUE THREAD

**Issue by mesqueeb** [CyCraft/starkdown#4]
It seems like a url like this will not properly handle. Starkdown tries to make an `<hr />` here:

```
[test.com/---/hello](test.com/---/hello)
// expected
<a src="test.com/---/hello">test.com/---/hello</a>
```
same for bold, italic, etc...
```
[app_.test.com/_](app_.test.com/_)
// expected
<a src="app_.test.com/_">app_.test.com/_</a>
```

**Comment by laquasicinque** [comment]
```md
[app_.test.com/_](app_.test.com/_)
// expected
<a src="app_.test.com/_">app_.test.com/_</a>
```
is actually not expected, there is a bug here but the actual expected result should be
```md
[app_.test.com/_](app_.test.com/_)
// expected
<a src="app_.test.com/_">app<em>.test.com/</em></a>
```
because there's nothing special about the text inside the parenthesis, especially in the case above where it doesn't even necessarily just match a url (no http(s)), they are parsed just like markdown, if you want the result you put in you have to escape the `_`

**Comment by laquasicinque** [comment]
For the first example, not sure if I fixed the second bug fixed the first but I couldn't get it to error how you said either

**Comment by mesqueeb** [comment]
@laquasicinque thanks for this ! The p tag I omited because I opted to not use p tag for inline tags like the a tag. 

Inside the a tag it's ok to still apply markdown I guess. But adding paragraphs feels a bit off..?

I will probably merge and release starkdown later this week!
